# -*- coding: utf-8 -*-

BRANCH_ALL = 0
BRANCH_HOKAIDO = 1
BRANCH_TOHOKU = 2
BRANCH_KANTO_SINETU = 3
BRANCH_TOKAI_HOKURIKU = 4
BRANCH_KINKI = 5
BRANCH_CYUGOKU = 6
BRANCH_SHIKOKU = 7
BRANCH_KYUSYU = 8

BRANCH_LIST = [BRANCH_HOKAIDO, BRANCH_TOHOKU, BRANCH_KANTO_SINETU, BRANCH_TOKAI_HOKURIKU,
               BRANCH_KINKI, BRANCH_CYUGOKU, BRANCH_SHIKOKU, BRANCH_KYUSYU]
